# Check CLI diagnostics separately from generated output and exit status.
if(SCENARIO STREQUAL "decode_only")
  set(input "${SOURCE_DIR}/tests/fixtures/simdjson_decode_only.hpp")
elseif(SCENARIO STREQUAL "supported")
  set(input "${SOURCE_DIR}/examples/basic/user.hpp")
elseif(SCENARIO STREQUAL "prohibited")
  set(input "${SOURCE_DIR}/tests/fixtures/simdjson_prohibited_encode.hpp")
else()
  message(FATAL_ERROR "Unknown diagnostic scenario: ${SCENARIO}")
endif()

set(output "${BINARY_DIR}/diagnostic_${SCENARIO}.cjm.hpp")
# A fatal error must leave existing output untouched.
file(WRITE "${output}" "diagnostic-test-sentinel\n")
execute_process(
  COMMAND "${CJM_EXECUTABLE}" generate --backend simdjson
          --input "${input}" --output "${output}"
  RESULT_VARIABLE status
  OUTPUT_VARIABLE stdout
  ERROR_VARIABLE stderr
)
file(READ "${output}" header)

function(require_contains text fragment)
  string(FIND "${text}" "${fragment}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "Missing: ${fragment}\nstdout: ${stdout}\nstderr: ${stderr}")
  endif()
endfunction()

function(require_absent text fragment)
  string(FIND "${text}" "${fragment}" position)
  if(NOT position EQUAL -1)
    message(FATAL_ERROR "Unexpected: ${fragment}\nstdout: ${stdout}\nstderr: ${stderr}")
  endif()
endfunction()

if(SCENARIO STREQUAL "prohibited")
  if(NOT status STREQUAL "1")
    message(FATAL_ERROR "Expected generation failure, got ${status}: ${stderr}")
  endif()
  require_contains("${stderr}" "model 'app::Prohibited'")
  require_contains("${stderr}" "field 'ratio'")
  require_contains("${stderr}" "json field 'amount'")
  require_contains("${stderr}" "C++ type 'long double'")
  require_contains("${stderr}" "encoding does not support long double without narrowing")
  require_absent("${stderr}" "cjm: warning:")
  require_absent("${stdout}" "cjm: generated")
  if(NOT header STREQUAL "diagnostic-test-sentinel\n")
    message(FATAL_ERROR "Fatal generation failure overwrote the existing output")
  endif()
else()
  if(NOT status STREQUAL "0")
    message(FATAL_ERROR "Expected success, got ${status}: ${stderr}")
  endif()
  require_contains("${stdout}" "cjm: generated")
  require_absent("${stdout}" "cjm: warning:")
  if(SCENARIO STREQUAL "supported")
    if(NOT stderr STREQUAL "")
      message(FATAL_ERROR "Supported model emitted diagnostics: ${stderr}")
    endif()
    require_contains("${header}" "to_json<")
  else()
    string(REGEX MATCHALL "cjm: warning: simdjson backend:" warnings "${stderr}")
    list(LENGTH warnings count)
    if(NOT count EQUAL 2)
      message(FATAL_ERROR "Expected exactly two warnings: ${stderr}")
    endif()
    require_contains("${stderr}" "model 'app::DecodeOnly', field 'scores', json field 'points', C++ type 'std::vector<int>'")
    require_contains("${stderr}" "model 'app::Parent'")
    require_contains("${stderr}" "nested model 'app::DecodeOnly' has no available encoder")
    require_contains("${stderr}" "generated decoder only")
    require_absent("${stderr}" "backup")
    require_absent("${stderr}" "app::Supported")
    foreach(model IN ITEMS Supported DecodeOnly Parent)
      require_contains("${header}" "from_json<::app::${model}>")
    endforeach()
    require_contains("${header}" "to_json<::app::Supported>")
    require_absent("${header}" "to_json<::app::DecodeOnly>")
    require_absent("${header}" "to_json<::app::Parent>")
  endif()
endif()
