// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <new>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    trailing_content,
    expected_object,
    expected_array,
    expected_bool,
    expected_string,
    expected_integer,
    expected_unsigned_integer,
    expected_number,
    invalid_enum_string,
    integer_overflow,
    floating_point_overflow,
    fixed_array_extent_mismatch,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

#ifndef CJM_SIMDJSON_ENCODE_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_ENCODE_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

using EncodePathSegmentKind = DecodePathSegmentKind;
using EncodePathSegment = DecodePathSegment;

enum class EncodeErrorCode {
    none,
    invalid_utf8_string,
    invalid_utf8_key,
    non_finite_number,
    invalid_enum_value,
    output_failure,
    allocation_failure,
    size_limit_exceeded
};

struct EncodeError {
    EncodeErrorCode code = EncodeErrorCode::none;
    std::vector<EncodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<std::string> to_json(
    const T& value,
    EncodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::User& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.
    bool has_name = false;
    bool has_age = false;

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "name") {
            std::string_view decoded_name_view;
            runtime_error = field.value().get_string().get(decoded_name_view);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_string;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "name", 0});
                error.runtime_error = runtime_error;
                return false;
            }
            value.name.assign(decoded_name_view.begin(), decoded_name_view.end());
            has_name = true;
            continue;
        }
        if (key == "age") {
            using target_type = decltype(value.age);
            std::int64_t decoded_age = 0;
            runtime_error = field.value().get_int64().get(decoded_age);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_integer;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "age", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            const auto target_min = static_cast<std::int64_t>(
                (std::numeric_limits<target_type>::min)());
            const auto target_max = static_cast<std::int64_t>(
                (std::numeric_limits<target_type>::max)());
            if (decoded_age < target_min || decoded_age > target_max) {
                error.code = DecodeErrorCode::integer_overflow;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "age", 0});
                return false;
            }

            value.age = static_cast<target_type>(decoded_age);
            has_age = true;
            continue;
        }
    }

    // 3. Verify that every required field was present.
    if (!has_name) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "name", 0});
        return false;
    }
    if (!has_age) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "age", 0});
        return false;
    }

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::User>
from_json<::User>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::User value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson

namespace cjm::simdjson::detail {

inline bool encode_object(
    ::simdjson::builder::string_builder& builder,
    const ::User& value,
    EncodeError& error) {
    builder.start_object();
    bool first_field = true;
    if (!::simdjson::validate_utf8(value.name)) {
        error.code = EncodeErrorCode::invalid_utf8_string;
        error.path = {{EncodePathSegmentKind::field, "name", 0}};
        error.runtime_error = ::simdjson::UTF8_ERROR;
        return false;
    }
    if (!first_field) {
        builder.append_comma();
    }
    first_field = false;
    builder.escape_and_append_with_quotes("name");
    builder.append_colon();
    builder.escape_and_append_with_quotes(value.name);
    if (!first_field) {
        builder.append_comma();
    }
    first_field = false;
    builder.escape_and_append_with_quotes("age");
    builder.append_colon();
    builder.append(value.age);
    builder.end_object();
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<std::string>
to_json<::User>(
    const ::User& value,
    EncodeError& error) {
    error = {};
    try {
        ::simdjson::builder::string_builder builder;
        const bool model_valid =
            detail::encode_object(builder, value, error);
        std::string_view view;
        const auto runtime_error = builder.view().get(view);
        if (runtime_error != ::simdjson::SUCCESS) {
            error.path.clear();
            error.code = EncodeErrorCode::output_failure;
            error.runtime_error = runtime_error;
            return std::nullopt;
        }
        if (!model_valid) {
            return std::nullopt;
        }
        return std::string(view);
    } catch (const std::bad_alloc&) {
        error.path.clear();
        error.code = EncodeErrorCode::allocation_failure;
        error.runtime_error = ::simdjson::SUCCESS;
        return std::nullopt;
    } catch (const std::length_error&) {
        error.path.clear();
        error.code = EncodeErrorCode::size_limit_exceeded;
        error.runtime_error = ::simdjson::SUCCESS;
        return std::nullopt;
    }
}

} // namespace cjm::simdjson
