// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    trailing_content,
    expected_object,
    expected_array,
    expected_bool,
    expected_string,
    expected_integer,
    expected_unsigned_integer,
    invalid_enum_string,
    integer_overflow,
    fixed_array_extent_mismatch,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::MapValues& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.
    bool has_counts = false;
    bool has_labels = false;

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "counts") {
            ::simdjson::ondemand::object decoded_counts_object;
            runtime_error = field.value().get_object().get(decoded_counts_object);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_object;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "counts", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.counts.clear();
            for (auto decoded_counts_entry : decoded_counts_object) {
                std::string_view decoded_counts_key;
                runtime_error = decoded_counts_entry.unescaped_key().get(decoded_counts_key);
                if (runtime_error) {
                    error.code = DecodeErrorCode::syntax_error;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "counts", 0});
                    error.runtime_error = runtime_error;
                    return false;
                }
                std::int32_t decoded_counts_value{};
                using target_type = decltype(decoded_counts_value);
                std::int64_t decoded_counts = 0;
                runtime_error = decoded_counts_entry.value().get_int64().get(decoded_counts);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_integer;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "counts", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::field, std::string(decoded_counts_key), 0});
                    error.runtime_error = runtime_error;
                    return false;
                }

                const auto target_min = static_cast<std::int64_t>(
                    (std::numeric_limits<target_type>::min)());
                const auto target_max = static_cast<std::int64_t>(
                    (std::numeric_limits<target_type>::max)());
                if (decoded_counts < target_min || decoded_counts > target_max) {
                    error.code = DecodeErrorCode::integer_overflow;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "counts", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::field, std::string(decoded_counts_key), 0});
                    return false;
                }

                decoded_counts_value = static_cast<target_type>(decoded_counts);
                value.counts[std::string(decoded_counts_key)] = decoded_counts_value;
            }
            has_counts = true;
            continue;
        }
        if (key == "labels") {
            ::simdjson::ondemand::object decoded_labels_object;
            runtime_error = field.value().get_object().get(decoded_labels_object);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_object;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "labels", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.labels.clear();
            for (auto decoded_labels_entry : decoded_labels_object) {
                std::string_view decoded_labels_key;
                runtime_error = decoded_labels_entry.unescaped_key().get(decoded_labels_key);
                if (runtime_error) {
                    error.code = DecodeErrorCode::syntax_error;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "labels", 0});
                    error.runtime_error = runtime_error;
                    return false;
                }
                std::string decoded_labels_value{};
                std::string_view decoded_labels_view;
                runtime_error = decoded_labels_entry.value().get_string().get(decoded_labels_view);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_string;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "labels", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::field, std::string(decoded_labels_key), 0});
                    error.runtime_error = runtime_error;
                    return false;
                }
                decoded_labels_value.assign(decoded_labels_view.begin(), decoded_labels_view.end());
                value.labels[std::string(decoded_labels_key)] = decoded_labels_value;
            }
            has_labels = true;
            continue;
        }
    }

    // 3. Verify that every required field was present.
    if (!has_counts) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "counts", 0});
        return false;
    }
    if (!has_labels) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "labels", 0});
        return false;
    }

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::MapValues>
from_json<::MapValues>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::MapValues value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson
