// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <new>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    trailing_content,
    expected_object,
    expected_array,
    expected_bool,
    expected_string,
    expected_integer,
    expected_unsigned_integer,
    expected_number,
    invalid_enum_string,
    integer_overflow,
    floating_point_overflow,
    fixed_array_extent_mismatch,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

#ifndef CJM_SIMDJSON_ENCODE_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_ENCODE_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

using EncodePathSegmentKind = DecodePathSegmentKind;
using EncodePathSegment = DecodePathSegment;

enum class EncodeErrorCode {
    none,
    invalid_utf8_string,
    invalid_utf8_key,
    non_finite_number,
    invalid_enum_value,
    output_failure,
    allocation_failure,
    size_limit_exceeded
};

struct EncodeError {
    EncodeErrorCode code = EncodeErrorCode::none;
    std::vector<EncodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<std::string> to_json(
    const T& value,
    EncodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::FloatingValues& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.
    bool has_ratio = false;
    bool has_amount = false;

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "ratio") {
            using target_type = decltype(value.ratio);
            double decoded_ratio = 0;
            runtime_error = field.value().get_double().get(decoded_ratio);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_number;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "ratio", 0});
                error.runtime_error = runtime_error;
                return false;
            }
            const double target_max = static_cast<double>(
                (std::numeric_limits<target_type>::max)());
            if (decoded_ratio < -target_max || decoded_ratio > target_max) {
                error.code = DecodeErrorCode::floating_point_overflow;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "ratio", 0});
                error.runtime_error = ::simdjson::SUCCESS;
                return false;
            }
            value.ratio = static_cast<target_type>(decoded_ratio);
            has_ratio = true;
            continue;
        }
        if (key == "amount") {
            using target_type = decltype(value.amount);
            double decoded_amount = 0;
            runtime_error = field.value().get_double().get(decoded_amount);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_number;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "amount", 0});
                error.runtime_error = runtime_error;
                return false;
            }
            const double target_max = static_cast<double>(
                (std::numeric_limits<target_type>::max)());
            if (decoded_amount < -target_max || decoded_amount > target_max) {
                error.code = DecodeErrorCode::floating_point_overflow;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "amount", 0});
                error.runtime_error = ::simdjson::SUCCESS;
                return false;
            }
            value.amount = static_cast<target_type>(decoded_amount);
            has_amount = true;
            continue;
        }
    }

    // 3. Verify that every required field was present.
    if (!has_ratio) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "ratio", 0});
        return false;
    }
    if (!has_amount) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "amount", 0});
        return false;
    }

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::FloatingValues>
from_json<::FloatingValues>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::FloatingValues value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson
