// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    trailing_content,
    expected_object,
    expected_array,
    expected_bool,
    expected_string,
    expected_integer,
    expected_unsigned_integer,
    invalid_enum_string,
    integer_overflow,
    fixed_array_extent_mismatch,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::GroupedItem& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.
    bool has_id = false;

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "id") {
            using target_type = decltype(value.id);
            std::int64_t decoded_id = 0;
            runtime_error = field.value().get_int64().get(decoded_id);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_integer;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "id", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            const auto target_min = static_cast<std::int64_t>(
                (std::numeric_limits<target_type>::min)());
            const auto target_max = static_cast<std::int64_t>(
                (std::numeric_limits<target_type>::max)());
            if (decoded_id < target_min || decoded_id > target_max) {
                error.code = DecodeErrorCode::integer_overflow;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "id", 0});
                return false;
            }

            value.id = static_cast<target_type>(decoded_id);
            has_id = true;
            continue;
        }
    }

    // 3. Verify that every required field was present.
    if (!has_id) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "id", 0});
        return false;
    }

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::GroupedItem>
from_json<::GroupedItem>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::GroupedItem value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::GroupedCatalog& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.
    bool has_groups = false;

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "groups") {
            ::simdjson::ondemand::object decoded_groups_object;
            runtime_error = field.value().get_object().get(decoded_groups_object);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_object;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "groups", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.groups.clear();
            for (auto decoded_groups_entry : decoded_groups_object) {
                std::string_view decoded_groups_key;
                runtime_error = decoded_groups_entry.unescaped_key().get(decoded_groups_key);
                if (runtime_error) {
                    error.code = DecodeErrorCode::syntax_error;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "groups", 0});
                    error.runtime_error = runtime_error;
                    return false;
                }
                std::vector<GroupedItem> decoded_groups_mapped_value{};
                ::simdjson::ondemand::array decoded_groups_array;
                runtime_error = decoded_groups_entry.value().get_array().get(decoded_groups_array);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_array;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "groups", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::field, std::string(decoded_groups_key), 0});
                    error.runtime_error = runtime_error;
                    return false;
                }

                decoded_groups_mapped_value.clear();
                std::size_t decoded_groups_index = 0;
                for (auto decoded_groups_element : decoded_groups_array) {
                    ::simdjson::ondemand::object decoded_groups_object;
                    runtime_error = decoded_groups_element.get_object().get(decoded_groups_object);
                    if (runtime_error) {
                        error.code = DecodeErrorCode::expected_object;
                        error.path.push_back(
                            {DecodePathSegmentKind::field, "groups", 0});
                        error.path.push_back(
                            {DecodePathSegmentKind::field, std::string(decoded_groups_key), 0});
                        error.path.push_back(
                            {DecodePathSegmentKind::index, "", decoded_groups_index});
                        error.runtime_error = runtime_error;
                        return false;
                    }
                    ::GroupedItem decoded_groups_value{};
                    if (!detail::decode_object(decoded_groups_object, decoded_groups_value, error)) {
                        error.path.insert(
                            error.path.begin(),
                            {DecodePathSegmentKind::index, "", decoded_groups_index});
                        error.path.insert(
                            error.path.begin(),
                            {DecodePathSegmentKind::field, std::string(decoded_groups_key), 0});
                        error.path.insert(
                            error.path.begin(),
                            {DecodePathSegmentKind::field, "groups", 0});
                        return false;
                    }
                    decoded_groups_mapped_value.push_back(decoded_groups_value);
                    ++decoded_groups_index;
                }
                value.groups[std::string(decoded_groups_key)] = decoded_groups_mapped_value;
            }
            has_groups = true;
            continue;
        }
    }

    // 3. Verify that every required field was present.
    if (!has_groups) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "groups", 0});
        return false;
    }

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::GroupedCatalog>
from_json<::GroupedCatalog>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::GroupedCatalog value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson
