// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    trailing_content,
    expected_object,
    expected_array,
    expected_bool,
    expected_string,
    expected_integer,
    expected_unsigned_integer,
    invalid_enum_string,
    integer_overflow,
    fixed_array_extent_mismatch,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::OptionalScalarValues& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "maybe_enabled") {
            value.maybe_enabled = std::nullopt;
            if (field.value().is_null()) {
                continue;
            }
            bool decoded_maybe_enabled_value{};
            runtime_error = field.value().get_bool().get(decoded_maybe_enabled_value);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_bool;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_enabled", 0});
                error.runtime_error = runtime_error;
                return false;
            }
            value.maybe_enabled = decoded_maybe_enabled_value;
            continue;
        }
        if (key == "maybe_count") {
            value.maybe_count = std::nullopt;
            if (field.value().is_null()) {
                continue;
            }
            std::int64_t decoded_maybe_count_value{};
            using target_type = decltype(decoded_maybe_count_value);
            std::int64_t decoded_maybe_count = 0;
            runtime_error = field.value().get_int64().get(decoded_maybe_count);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_integer;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_count", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            const auto target_min = static_cast<std::int64_t>(
                (std::numeric_limits<target_type>::min)());
            const auto target_max = static_cast<std::int64_t>(
                (std::numeric_limits<target_type>::max)());
            if (decoded_maybe_count < target_min || decoded_maybe_count > target_max) {
                error.code = DecodeErrorCode::integer_overflow;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_count", 0});
                return false;
            }

            decoded_maybe_count_value = static_cast<target_type>(decoded_maybe_count);
            value.maybe_count = decoded_maybe_count_value;
            continue;
        }
        if (key == "maybe_limit") {
            value.maybe_limit = std::nullopt;
            if (field.value().is_null()) {
                continue;
            }
            std::uint64_t decoded_maybe_limit_value{};
            using target_type = decltype(decoded_maybe_limit_value);
            std::uint64_t decoded_maybe_limit = 0;
            runtime_error = field.value().get_uint64().get(decoded_maybe_limit);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_unsigned_integer;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_limit", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            const auto target_max = static_cast<std::uint64_t>(
                (std::numeric_limits<target_type>::max)());
            if (decoded_maybe_limit > target_max) {
                error.code = DecodeErrorCode::integer_overflow;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_limit", 0});
                return false;
            }

            decoded_maybe_limit_value = static_cast<target_type>(decoded_maybe_limit);
            value.maybe_limit = decoded_maybe_limit_value;
            continue;
        }
        if (key == "maybe_name") {
            value.maybe_name = std::nullopt;
            if (field.value().is_null()) {
                continue;
            }
            std::string decoded_maybe_name_value{};
            std::string_view decoded_maybe_name_view;
            runtime_error = field.value().get_string().get(decoded_maybe_name_view);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_string;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_name", 0});
                error.runtime_error = runtime_error;
                return false;
            }
            decoded_maybe_name_value.assign(decoded_maybe_name_view.begin(), decoded_maybe_name_view.end());
            value.maybe_name = decoded_maybe_name_value;
            continue;
        }
        if (key == "maybe_status") {
            value.maybe_status = std::nullopt;
            if (field.value().is_null()) {
                continue;
            }
            ::Status decoded_maybe_status_value{};
            std::string_view decoded_maybe_status_view;
            runtime_error = field.value().get_string().get(decoded_maybe_status_view);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_string;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_status", 0});
                error.runtime_error = runtime_error;
                return false;
            }
            bool decoded_maybe_status_matches = false;
            if (decoded_maybe_status_view == "Active") {
                decoded_maybe_status_value = ::Status::Active;
                decoded_maybe_status_matches = true;
            }
            if (decoded_maybe_status_view == "Disabled") {
                decoded_maybe_status_value = ::Status::Disabled;
                decoded_maybe_status_matches = true;
            }
            if (!decoded_maybe_status_matches) {
                error.code = DecodeErrorCode::invalid_enum_string;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "maybe_status", 0});
                return false;
            }
            value.maybe_status = decoded_maybe_status_value;
            continue;
        }
    }

    // 3. Verify that every required field was present.

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::OptionalScalarValues>
from_json<::OptionalScalarValues>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::OptionalScalarValues value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson
