// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    trailing_content,
    expected_object,
    expected_array,
    expected_bool,
    expected_string,
    expected_integer,
    expected_unsigned_integer,
    invalid_enum_string,
    integer_overflow,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson::detail {

inline bool decode_object(
    ::simdjson::ondemand::object& object,
    ::VectorValues& value,
    DecodeError& error) {
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;

    // 1. Track required fields for this object.
    bool has_tags = false;
    bool has_flags = false;
    bool has_scores = false;
    bool has_limits = false;
    bool has_statuses = false;

    // 2. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return false;
        }

        if (key == "tags") {
            ::simdjson::ondemand::array decoded_tags_array;
            runtime_error = field.value().get_array().get(decoded_tags_array);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_array;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "tags", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.tags.clear();
            std::size_t decoded_tags_index = 0;
            for (auto decoded_tags_element : decoded_tags_array) {
                std::string decoded_tags_value{};
                std::string_view decoded_tags_view;
                runtime_error = decoded_tags_element.get_string().get(decoded_tags_view);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_string;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "tags", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_tags_index});
                    error.runtime_error = runtime_error;
                    return false;
                }
                decoded_tags_value.assign(decoded_tags_view.begin(), decoded_tags_view.end());
                value.tags.push_back(decoded_tags_value);
                ++decoded_tags_index;
            }
            has_tags = true;
            continue;
        }
        if (key == "flags") {
            ::simdjson::ondemand::array decoded_flags_array;
            runtime_error = field.value().get_array().get(decoded_flags_array);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_array;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "flags", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.flags.clear();
            std::size_t decoded_flags_index = 0;
            for (auto decoded_flags_element : decoded_flags_array) {
                bool decoded_flags_value{};
                runtime_error = decoded_flags_element.get_bool().get(decoded_flags_value);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_bool;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "flags", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_flags_index});
                    error.runtime_error = runtime_error;
                    return false;
                }
                value.flags.push_back(decoded_flags_value);
                ++decoded_flags_index;
            }
            has_flags = true;
            continue;
        }
        if (key == "scores") {
            ::simdjson::ondemand::array decoded_scores_array;
            runtime_error = field.value().get_array().get(decoded_scores_array);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_array;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "scores", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.scores.clear();
            std::size_t decoded_scores_index = 0;
            for (auto decoded_scores_element : decoded_scores_array) {
                std::int32_t decoded_scores_value{};
                using target_type = decltype(decoded_scores_value);
                std::int64_t decoded_scores = 0;
                runtime_error = decoded_scores_element.get_int64().get(decoded_scores);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_integer;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "scores", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_scores_index});
                    error.runtime_error = runtime_error;
                    return false;
                }

                const auto target_min = static_cast<std::int64_t>(
                    (std::numeric_limits<target_type>::min)());
                const auto target_max = static_cast<std::int64_t>(
                    (std::numeric_limits<target_type>::max)());
                if (decoded_scores < target_min || decoded_scores > target_max) {
                    error.code = DecodeErrorCode::integer_overflow;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "scores", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_scores_index});
                    return false;
                }

                decoded_scores_value = static_cast<target_type>(decoded_scores);
                value.scores.push_back(decoded_scores_value);
                ++decoded_scores_index;
            }
            has_scores = true;
            continue;
        }
        if (key == "limits") {
            ::simdjson::ondemand::array decoded_limits_array;
            runtime_error = field.value().get_array().get(decoded_limits_array);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_array;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "limits", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.limits.clear();
            std::size_t decoded_limits_index = 0;
            for (auto decoded_limits_element : decoded_limits_array) {
                std::uint32_t decoded_limits_value{};
                using target_type = decltype(decoded_limits_value);
                std::uint64_t decoded_limits = 0;
                runtime_error = decoded_limits_element.get_uint64().get(decoded_limits);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_unsigned_integer;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "limits", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_limits_index});
                    error.runtime_error = runtime_error;
                    return false;
                }

                const auto target_max = static_cast<std::uint64_t>(
                    (std::numeric_limits<target_type>::max)());
                if (decoded_limits > target_max) {
                    error.code = DecodeErrorCode::integer_overflow;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "limits", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_limits_index});
                    return false;
                }

                decoded_limits_value = static_cast<target_type>(decoded_limits);
                value.limits.push_back(decoded_limits_value);
                ++decoded_limits_index;
            }
            has_limits = true;
            continue;
        }
        if (key == "statuses") {
            ::simdjson::ondemand::array decoded_statuses_array;
            runtime_error = field.value().get_array().get(decoded_statuses_array);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_array;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "statuses", 0});
                error.runtime_error = runtime_error;
                return false;
            }

            value.statuses.clear();
            std::size_t decoded_statuses_index = 0;
            for (auto decoded_statuses_element : decoded_statuses_array) {
                ::Status decoded_statuses_value{};
                std::string_view decoded_statuses_view;
                runtime_error = decoded_statuses_element.get_string().get(decoded_statuses_view);
                if (runtime_error) {
                    error.code = DecodeErrorCode::expected_string;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "statuses", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_statuses_index});
                    error.runtime_error = runtime_error;
                    return false;
                }
                bool decoded_statuses_matches = false;
                if (decoded_statuses_view == "Active") {
                    decoded_statuses_value = ::Status::Active;
                    decoded_statuses_matches = true;
                }
                if (decoded_statuses_view == "Disabled") {
                    decoded_statuses_value = ::Status::Disabled;
                    decoded_statuses_matches = true;
                }
                if (!decoded_statuses_matches) {
                    error.code = DecodeErrorCode::invalid_enum_string;
                    error.path.push_back(
                        {DecodePathSegmentKind::field, "statuses", 0});
                    error.path.push_back(
                        {DecodePathSegmentKind::index, "", decoded_statuses_index});
                    return false;
                }
                value.statuses.push_back(decoded_statuses_value);
                ++decoded_statuses_index;
            }
            has_statuses = true;
            continue;
        }
    }

    // 3. Verify that every required field was present.
    if (!has_tags) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "tags", 0});
        return false;
    }
    if (!has_flags) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "flags", 0});
        return false;
    }
    if (!has_scores) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "scores", 0});
        return false;
    }
    if (!has_limits) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "limits", 0});
        return false;
    }
    if (!has_statuses) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "statuses", 0});
        return false;
    }

    // 4. Report that this object was decoded successfully.
    return true;
}

} // namespace cjm::simdjson::detail

namespace cjm::simdjson {

template <>
inline std::optional<::VectorValues>
from_json<::VectorValues>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }
    // 3. Decode the root object into a new value.
    ::VectorValues value{};
    if (!detail::decode_object(object, value, error)) {
        return std::nullopt;
    }

    // 4. Reject non-whitespace content after the root object.
    if (!document.at_end()) {
        error.code = DecodeErrorCode::trailing_content;
        error.runtime_error = ::simdjson::TRAILING_CONTENT;
        return std::nullopt;
    }

    // 5. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson
