#include "backends/simdjson/cpp_generator.hpp"
#include "backends/simdjson/decoder.h"
#include "backends/simdjson/encoder.h"

#include <sstream>

namespace cjm::generator::simdjson {

GenerationResult generate_header(const metadata::ProjectModel& project) {
    const auto error = detail::validate_project(project);
    if (!error.empty()) {
        return GenerationResult{false, {}, error};
    }

    std::ostringstream header;
    header << "// This file was generated by CJM.\n"
           << "// Do not edit this file manually.\n"
           << "\n"
           << "#pragma once\n"
           << "\n"
           << "#include <simdjson.h>\n"
           << "\n"
           << "#include <cstddef>\n"
           << "#include <cmath>\n"
           << "#include <cstddef>\n"
           << "#include <cstdint>\n"
           << "#include <limits>\n"
           << "#include <new>\n"
           << "#include <optional>\n"
           << "#include <stdexcept>\n"
           << "#include <string>\n"
           << "#include <string_view>\n"
           << "#include <vector>\n"
           << "\n";

    detail::generate_decode_error_model(header);
    header << "\n";
    detail::generate_encode_error_model(header);

    std::set<std::string> encoded_models;
    for (const auto& type : project.types) {
        header << "\n";
        detail::generate_object_decode_function(header, type, project.enums);
        header << "\n";
        detail::generate_root_decode_function(header, type);
        bool can_encode = true;
        for (const auto& field : type.fields) {
            if (field.json.ignored) {
                continue;
            }

            if (!detail::is_supported_value_encode_type(field.type,
                                                        encoded_models)) {
                can_encode = false;
                break;
            }
        }
        if (can_encode) {
            header << "\n";
            detail::generate_scalar_object_encode_function(header, type,
                                                           project.enums);
            header << "\n";
            detail::generate_root_encode_function(header, type);

            encoded_models.insert(
                type.qualified_name.empty() ? type.name : type.qualified_name);
        }
    }
    return GenerationResult{true, header.str(), {}};
}

} // namespace cjm::generator::simdjson
