#include "backends/simdjson/cpp_generator.hpp"
#include "backends/simdjson/decoder.h"
#include "backends/simdjson/encoder.h"

#include <sstream>

namespace cjm::generator::simdjson {

GenerationResult generate_header(const metadata::ProjectModel& project) {
    const auto error = detail::validate_project(project);
    if (!error.empty()) {
        return GenerationResult{false, {}, error};
    }

    std::ostringstream header;
    header << "// This file was generated by CJM.\n"
           << "// Do not edit this file manually.\n"
           << "\n"
           << "#pragma once\n"
           << "\n"
           << "#include <simdjson.h>\n"
           << "\n"
           << "#include <cstddef>\n"
           << "#include <cmath>\n"
           << "#include <cstddef>\n"
           << "#include <cstdint>\n"
           << "#include <limits>\n"
           << "#include <new>\n"
           << "#include <optional>\n"
           << "#include <stdexcept>\n"
           << "#include <string>\n"
           << "#include <string_view>\n"
           << "#include <vector>\n"
           << "\n";

    detail::generate_decode_error_model(header);
    header << "\n";
    detail::generate_encode_error_model(header);

    for (const auto& type : project.types) {
        header << "\n";
        detail::generate_object_decode_function(header, type, project.enums);
        header << "\n";
        detail::generate_root_decode_function(header, type);
        bool scalar_only = true;
        for (const auto& field : type.fields) {
            if (field.json.ignored) {
                continue;
            }
            const auto kind = field.type.kind;
            const auto& type_name = field.type.qualified_name.empty()
                                        ? field.type.spelling
                                        : field.type.qualified_name;
            const bool supported_float =
                kind == metadata::FieldTypeKind::FloatingPoint &&
                (type_name == "float" || type_name == "double");
            if (kind != metadata::FieldTypeKind::Bool &&
                kind != metadata::FieldTypeKind::SignedInteger &&
                kind != metadata::FieldTypeKind::UnsignedInteger &&
                !supported_float) {
                scalar_only = false;
                break;
            }
        }
        if (scalar_only) {
            header << "\n";
            detail::generate_scalar_object_encode_function(header, type);
            header << "\n";
            detail::generate_root_encode_function(header, type);
        }
    }
    return GenerationResult{true, header.str(), {}};
}

} // namespace cjm::generator::simdjson
