#include "backends/simdjson/cpp_generator.hpp"
#include "backends/simdjson/decoder.h"
#include "backends/simdjson/encoder.h"

#include <sstream>

namespace cjm::generator::simdjson {

GenerationResult generate_header(const metadata::ProjectModel& project) {
    // Report prohibited encode mappings before checking decode support.
    const auto encode_error = detail::validate_encode_project(project);
    if (!encode_error.empty()) {
        return GenerationResult{false, {}, encode_error};
    }

    const auto error = detail::validate_decode_project(project);
    if (!error.empty()) {
        return GenerationResult{false, {}, error};
    }

    std::ostringstream header;
    header << "// This file was generated by CJM.\n"
           << "// Do not edit this file manually.\n"
           << "\n"
           << "#pragma once\n"
           << "\n"
           << "#include <simdjson.h>\n"
           << "\n"
           << "#include <cstddef>\n"
           << "#include <cmath>\n"
           << "#include <cstddef>\n"
           << "#include <cstdint>\n"
           << "#include <limits>\n"
           << "#include <new>\n"
           << "#include <optional>\n"
           << "#include <stdexcept>\n"
           << "#include <string>\n"
           << "#include <string_view>\n"
           << "#include <vector>\n"
           << "\n";

    detail::generate_decode_error_model(header);
    header << "\n";
    detail::generate_encode_error_model(header);

    std::set<std::string> encoded_models;
    std::vector<std::string> warnings;
    for (const auto& type : project.types) {
        header << "\n";
        detail::generate_object_decode_function(header, type, project.enums);
        header << "\n";
        detail::generate_root_decode_function(header, type);
        bool can_encode = true;
        for (const auto& field : type.fields) {
            if (field.json.ignored) {
                continue;
            }

            const auto reason = detail::unsupported_value_encode_reason(
                field.type, encoded_models);
            if (!reason.empty()) {
                const auto& model_name = type.qualified_name.empty()
                                             ? type.name
                                             : type.qualified_name;
                const auto& type_name = field.type.spelling.empty()
                                            ? field.type.qualified_name
                                            : field.type.spelling;
                warnings.push_back(
                    "model '" + model_name + "', field '" + field.name +
                    "', json field '" + field.json.name + "', C++ type '" +
                    type_name + "'; " + reason + "; generated decoder only");
                can_encode = false;
                break;
            }
        }
        if (can_encode) {
            header << "\n";
            detail::generate_scalar_object_encode_function(header, type,
                                                           project.enums);
            header << "\n";
            detail::generate_root_encode_function(header, type);

            encoded_models.insert(
                type.qualified_name.empty() ? type.name : type.qualified_name);
        }
    }
    return GenerationResult{true, header.str(), {}, warnings};
}

} // namespace cjm::generator::simdjson
